### ISSUE TITLE
digris-edimcast2edi: UDP packet size 1328 not multiple of 188

### ISSUE THREAD

**Issue by andimik** [digris/digris-edi-zmq-bridge#2]
I 'd like to use it for an alternative for `fedi2eti` but there seems to be a bug, which is caused by https://github.com/digris/digris-edi-zmq-bridge/blob/99fc671ed18c25baf25affe1c95157a17f600e8b/src/mpe_deframer.cpp#L57-L63

# digris-edimcast2edi 

a) on 7E tune to the German MPE transponder: `tune-s2 12567 V 17015 -system DVB-S2 -lnb UNIVERSAL -modulation 8PSK -fec 2/3`
b) `dvbstream -c 0 8192 -i 127.0.0.1 -r 5000`
c) `digris-edimcast2edi -m 127.0.0.1 -p 5000 -b 127.0.0.1 -F 101:239.16.242.17:60017 -l 8971`
d) this will give the following errors and there is no chance to use dablin_gtk then (no data sent to port 8971):

```
UDP packet size 1328 not multiple of 188
``` 
Tested with dbc6d9170b85788d5fe892c2a0892f88fedd82ef

![grafik](https://github.com/user-attachments/assets/f85a2454-934f-4421-a2ae-44a79349d211)

I have also tested on 23.5E with the MPE transmissions of Bundesmux 1 and 2, same output.

`-v` does not show more than these error lines.

Can you advice me, if my syntax was wrong?

# fedi2eti

a) on 7E tune to the German MPE transponder: `tune-s2 12567 V 17015 -system DVB-S2 -lnb UNIVERSAL -modulation 8PSK -fec 2/3`
b) `dvbstream -o O -c 0 101 | fedi2eti 101 239.132.1.50 5004 | dablin_gtk`
c) I can listen to the SWR BW S multiplex

![grafik](https://github.com/user-attachments/assets/889437df-82e2-4066-8138-cb0b13ea62c3)

**Comment by YoannQueret** [comment]
dvbstream output is RTP, not UDP. It's probably why you have this error and also because we don't use dvbstream as input for MPE
@mpbraendli can you confirm ?

**Comment by andimik** [comment]
I found the correct syntax: I need to set dvbstream with `-udp` parameter.

Thanks for pointing that, therefore closing.

**Comment by mpbraendli** [comment]
@andimik  I've added an example to the README, is that correct?

https://github.com/digris/digris-edi-zmq-bridge/blob/7a7edad98760dd1ea3d1ddc1ecb48358589e62c5/README.md?plain=1#L75

**Comment by andimik** [comment]
Have not 100% checked the syntax, but looks good.

Well, I fear this text is too specific, like "RTP header". But why not say, that for MPE `dvbstream` needs to used with the parameter `-udp`  ...

Maybe a hint: the syntax for MPE is different than for `fedi2eti` as the PID, IP and Port need to be separated with a space there, but here with a `:`. Is this intended?

**Comment by mpbraendli** [comment]
We're still discovering what makes most sense. Not everybody is using dvbstream, @YoannQueret for example has a dedicated SAT reception device.

If we can write the README so that it both explains what is expected, and give useful examples that work, then the README will be useful to both experts and novices.
