### ISSUE TITLE
Missing IP and Port for Parameter -G

### ISSUE THREAD

**Issue by andimik** [digris/digris-edi-zmq-bridge#3]
According to a post in a forum there is no chance to use `digris-edimcast2edi` for Norwegian NRK and Riks Mux on 0.8W as the `-G` does not accept an IP Address and Port, as all 8 streams have the same MIS.

See https://www.satellites.co.uk/forums/threads/dab-on-1-west-generic-stream.182304/post-1165193

I cannot receive that transponder any more, so I need to ask the person who reported that.

**Comment by mpbraendli** [comment]
I've added an IP and port filter to `-G` option, with the `MIS:IP:PORT` format. Can you get someone to try this out?

**Comment by andimik** [comment]
https://github.com/digris/digris-edi-zmq-bridge/commit/36996ee7c08e90aca38130fd7ac56d34e34dc069#diff-97A395CD5699DAC54D5AA4789DA2CACBR54

This should be mis, not mid.

**Comment by andimik** [comment]
https://www.satellites.co.uk/forums/threads/dab-on-1-west-generic-stream.182304/post-1165342

Another user confirmed that it works for the Norwegian DAB now.

Therefore, I will close it.

**Comment by mpbraendli** [comment]
Very happy to hear this, thanks a lot!
